
baseURL = "https://FerCipriani.github.io/linkblog/"
languageCode = "es"
title = "LinkBlog"
theme = "PaperMod"

[author]
name = "Fer Cipriani"

[taxonomies]
  tag = "tags"

[params]
  author = "Fer Cipriani"
  ShowReadingTime = false
  ShowShareButtons = false
  customCSS = [
    "css/pills.css",
    "css/typography.css"
  ]

paginate = 30

[menu]

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20
  


